name: perturbation-test
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Run the test
          pip install -r requirements.txt
          python run_perturbation_test.py
          
          # Report the diff
          echo "## Workspace vs. Main" > report.md
          git fetch --prune
          dvc metrics diff main --targets test_score.json --show-md >> report.md
          
          # Print out the failure modes
          echo "## Failure modes" >> report.md
          cat failure_modes.txt >> report.md
          
          # Send it!
          cml-send-comment report.md
